services:
  backend:
    build:
      context: ./backend
      target: ${DEBUG_STAGE:-run}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "5005:5005"
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_URL=http://${FRONTEND_HOST}:${FRONTEND_PORT}
      - DEBUG_PORT=5005

      # Configurations that get loaded into chargers
      # Charger 1
      - ID_TAG_1=${ID_TAG_1:-test}
      - CENTRAL_SYSTEM_URL_1=${CENTRAL_SYSTEM_URL_1:-ws://host.docker.internal:9000}
      - METER_VALUE_SAMPLE_INTERVAL_1=${METER_VALUE_SAMPLE_INTERVAL_1:-30}
      - METER_VALUES_SAMPLED_DATA_1=${METER_VALUES_SAMPLED_DATA_1:-ENERGY_ACTIVE_IMPORT_REGISTER}
      # Charger 2
      - ID_TAG_2=${ID_TAG_2:-test}
      - CENTRAL_SYSTEM_URL_2=${CENTRAL_SYSTEM_URL_2:-ws://host.docker.internal:9000}
      - METER_VALUE_SAMPLE_INTERVAL_2=${METER_VALUE_SAMPLE_INTERVAL_2:-30}
      - METER_VALUES_SAMPLED_DATA_2=${METER_VALUES_SAMPLED_DATA_2:-ENERGY_ACTIVE_IMPORT_REGISTER}
      # Charger 3
      - ID_TAG_3=${ID_TAG_3:-test}
      - CENTRAL_SYSTEM_URL_3=${CENTRAL_SYSTEM_URL_3:-ws://host.docker.internal:9000}
      - METER_VALUE_SAMPLE_INTERVAL_3=${METER_VALUE_SAMPLE_INTERVAL_3:-30}
      - METER_VALUES_SAMPLED_DATA_3=${METER_VALUES_SAMPLED_DATA_3:-ENERGY_ACTIVE_IMPORT_REGISTER}
    profiles:
      - core
      - integration-test
      - unit_test
    networks:
      - core-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend-test:
    depends_on:
      - backend
    build:
      context: ./backend
      target: test
    profiles:
      - unit_test

  frontend:
    build:
      context: ./frontend
      target: run
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://${BACKEND_HOST}:${BACKEND_PORT}
    profiles:
      - core
      - integration-test
      - unit_test
    networks:
      - core-network

  frontend-test:
    depends_on:
      - frontend
    build:
      context: ./frontend
      target: test
    profiles:
      - unit_test

  dummy-server:
    build:
      context: ./dummy_server
    ports:
      - "9000:9000" # WebSocket port
      - "9001:9001" # HTTP port
    profiles:
      - dummy-server
      - integration-test
    environment:
      - NODE_ENV=production
      - NORMAL_MODE=${NORMAL_MODE}
    networks:
      - core-network

  integration-test:
    build:
      context: ./integration_test
    depends_on:
      - dummy-server
      - backend
      - frontend
    profiles:
      - integration-test
    environment:
      - BACKEND_URL=http://${BACKEND_HOST}:${BACKEND_PORT}
      - FRONTEND_URL=http://${FRONTEND_HOST}:${FRONTEND_PORT}
    volumes:
      - ./integration_test:/app/integration_test
    networks:
      - core-network

networks:
  core-network:
    driver: bridge
