services:
  backend:
    build:
      context: ./backend
      target: run
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_URL=http://${FRONTEND_HOST}:${FRONTEND_PORT}
  backend-test:
    depends_on:
      - backend
    build:
      context: ./backend
      target: test
    profiles:
     - test
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://${BACKEND_HOST}:${BACKEND_PORT}

