name: Prettier Check

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  prettier:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Prettier Check
        working-directory: ./frontend
        run: npx prettier --check src/**/*.js
